version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules: